name: starlord
channels:
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.9.12
  - pip:
      - matplotlib==3.5.2
      - torch==1.12.0
      - torchvision==0.13.0
      - numpy==1.23.0
      - tqdm
      - ultralytics

     
